IGNITE-3808 Reproducer for missing EntryProcessr invocation
This test reproduces IGNITE-3808. It is intermittent; every 3 or
4 invocations the test will fail with a message like this:

junit.framework.AssertionFailedError: Unexpected clear bit: 180424